### ISSUE TITLE
Why do you store certificates?

### ISSUE THREAD

**Issue by kelunik** [acmephp/core#6]
Why do you store the Let's Encrypt certificate (root / x1 / x2)?

**Comment by tgalopin** [comment]
To build the fullchain. How do you do in your library?

**Comment by kelunik** [comment]
There's an `rel="up"` link, see https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md#certificate-issuance

It's not a good idea to hardcode it, otherwise your automation will fail if X1 gets revoked or replaced, which will btw. soon be the case, because a new intermediate will be issued to ensure Windows XP compatibility.

Also, the root certificate shouldn't be in the fullchain, just the cert + intermediate.

**Comment by tgalopin** [comment]
Thanks for the explanations, I didn't know that. I'll make the change in the next release :) .

**Comment by kelunik** [comment]
This is especially relevant, as there are new X3 and X4 intermediate certificates now for Windows XP support.

**Comment by tgalopin** [comment]
Thanks, I'll do the change :)

**Comment by jderusse** [comment]
The full chain certificate is made of the chain and the certificate.

As defined in the letsencrypt cli https://github.com/letsencrypt/letsencrypt/blob/ebf0163983cfd5505fe32b7e88c528397f17922b/letsencrypt/storage.py#L812-L820

**Comment by tgalopin** [comment]
I figured this change is not as simple as I excepted given the current architecture of the core. We are working on a better architecture with @jderusse, including the testing-ca and the SSL library. For the moment I think I will simply make the change in the resources directory, but the following release should be using the dynamic chain.

Thanks for your help @kelunik!

**Comment by kelunik** [comment]
Same for the agreement btw. ;-)

**Comment by tgalopin** [comment]
I was thinking exactly the same :) .

**Comment by tgalopin** [comment]
I close this as the core is now using the new architecture. The implementation in the CLI should happen soon.
