### ISSUE TITLE
Is the DNS challenge supported in 1.0.0-alpha4?

### ISSUE THREAD

**Issue by kevinquinnyo** [acmephp/core#9]
Apologies in advance -- this is more of a question than a real "issue".

I notice while playing with this library (`1.0.0-alpha4`) that in `AcmePhp\Core\AbstractAcmeClient::doRequestChallenge()` it only returns a `Challenge` object if the challenge is of type "http-01".

Does that mean that in `1.0.0-alpha4` the only supported challenge is the "simpleHttp" challenge?  I'm confused because the request being made in that class seems to be `'type'  => 'dns'`, but then it seems to filter for an "http-01" challange type.  And it does respond with a `Challenge` object:

```php
        foreach ($response['challenges'] as $challenge) {
            if ('http-01' === $challenge['type']) {
            // [..snip..]
            return new Challenge($domain, $challenge['uri'], $token, $payload, $location);
```

Can I set a TXT record with the token supplied in the response, like:

```
_acme-challenge.example.com. 300 IN TXT "$this_is_the_token"
```

Or do I have to do the "simple http" challenge, by creating a file in the domain's `document_root` called:

```
./.well-known/acme-challenge/$this_is_the_token
```
?

Thanks for the great library, and I would really appreciate some education on this  :)

**Comment by tgalopin** [comment]
Hello @kevinquinnyo !

Thanks for your question!

Currently,the only supported challenge is indeed `http-01`. However, I did this choice for reasons that are no longer relevant, I'll change that in the next version.

For the moment, you can indeed create the token in your web root.

**Comment by tgalopin** [comment]
Hi @kevinquinnyo !

I am currently creating a single mono-repo for the project on https://github.com/acmephp/acmephp in order to have a single place where to develop. In this process, I will transform this repository in a read-only one where I will disable the issue tracker, so this issue will be closed. Please open a new one https://github.com/acmephp/acmephp if you want to continue the discussion :) !

**Comment by kevinquinnyo** [comment]
Thanks @tgalopin!
